### ISSUE TITLE
Error running documentation example "Hello Tweepy"

### ISSUE THREAD

**Issue by jlnabais** [tweepy/tweepy#630]
Can't get the example documentation "Hello Tweepy" to run:

http://tweepy.readthedocs.org/en/v3.2.0/getting_started.html#hello-tweepy

I'm running python 3.4.3 and tweepy 3.3.0 (installed via pip):

• [joaocasaltanabais@Joaos-MacBook-Pro:~/Projects/examples] $ python3.4 tweepy_example.py 
Traceback (most recent call last):
  File "tweepy_example.py", line 1, in <module>
    import tweepy
  File "/Users/joaocasaltanabais/Projects/examples/tweepy_example.py", line 3, in <module>
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
AttributeError: 'module' object has no attribute 'OAuthHandler'

Found some guidance in a thread in http://stackoverflow.com/questions/26075001/error-with-tweepy-oauthhandler

however if I change the code to:

```
from tweepy.auth import OAuthHandler

auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
```

I get:

• [joaocasaltanabais@Joaos-MacBook-Pro:~/Projects/examples] $ python3.4 tweepy_example.py 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tweepy_example.py", line 1, in <module>
    from tweepy.auth import OAuthHandler
  File "/Users/joaocasaltanabais/Projects/examples/tweepy_example.py", line 1, in <module>
    from tweepy.auth import OAuthHandler
ImportError: No module named 'tweepy.auth'; 'tweepy' is not a package

Can you please help?

Best,
João.

**Comment by johnkw** [comment]
There seems to be a lot of irrelevant information here.  Just run python by itself and manually type "import tweepy" - does that work?

**Comment by jlnabais** [comment]
No.

'''
• [joaocasaltanabais@Joaos-MacBook-Pro:~/Projects/examples] $ workon examples

• [joaocasaltanabais@Joaos-MacBook-Pro:~/Projects/examples] $ python3.4
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tweepy
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joaocasaltanabais/Projects/examples/tweepy.py", line 2, in <module>
    from tweepy.auth import OAuthHandler
ImportError: No module named 'tweepy.auth'; 'tweepy' is not a package
>>> 
'''

**Comment by johnkw** [comment]
Ok, so you haven't correctly installed tweepy then. Or you have installed it, and then overridden/broken it with whatever that "/Users/joaocasaltanabais/Projects/examples/tweepy.py" thing is.

**Comment by jlnabais** [comment]
I have installed it via pip:
```
• [joaocasaltanabais@Joaos-MacBook-Pro:~] $ pip install tweepy
```

With python2.7 is working:
```
• [joaocasaltanabais@Joaos-MacBook-Pro:~] $ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tweepy
>>> 
```

Should it not work with python3.4 also?

Thanks.

**Comment by jlnabais** [comment]
I'm sorry, you're right...renamed my "example" file and it's up and runnig.

Thanks,

Sorry.

**Comment by jlnabais** [comment]
I've got it working with python2.7, but I'm still having trouble getting it to work with python3.4:

Example:

```
import tweepy

auth = tweepy.OAuthHandler("", "")
auth.set_access_token("", "")

api = tweepy.API(auth)

public_tweets = api.home_timeline()
for tweet in public_tweets:
    print(tweet.text)

# Get the User object for twitter...
user = api.get_user('twitter')

print(user.screen_name)
print(user.followers_count)
for friend in user.friends():
   print(friend.screen_name)
```

Output (python2.7):
```
• [joaocasaltanabais@Joaos-MBP:~/Projects/examples] $ python tweepy_test.py
twitter
42631877
TwitterStage
womenux
university
TwitterWomen
TwitterUK
TwitterTurkey
TwitterSpain
TwitterShopping
TwitterSG
TwitterSeattle
TwitterSA
TwitterRussia
TwitterOpen
TwitterNL
TwitterNigeria
TwitterMENA
TwitterLatAm
TwitterLA
TwitterKenya
TwitterJP
```

OUTPUT (python3.4):
```
• [joaocasaltanabais@Joaos-MBP:~/Projects/examples] $ python3.4 tweepy_test.py
Traceback (most recent call last):
  File "tweepy_test.py", line 1, in <module>
    import tweepy
ImportError: No module named 'tweepy'
```
