### ISSUE TITLE
i have an issue with requirements 

### ISSUE THREAD

**Issue by ninuxhub** [tweepy/tweepy#564]
```bash
root@HOST:~# pip install tweepy
Downloading/unpacking tweepy
  Running setup.py egg_info for package tweepy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/root/build/tweepy/setup.py", line 17, in <module>
        install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/build/tweepy/setup.py", line 17, in <module>

    install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /root/build/tweepy
Storing complete log in /root/.pip/pip.log
```
please tel me if you need more details

**Comment by ninuxhub** [comment]
install 2.3.0 without an issue

**Comment by aiusepsi** [comment]
Try updating pip:
sudo pip install --upgrade pip

This fixed the problem for me.

**Comment by ninuxhub** [comment]
Ty i'll try that tonight and keep you in a loop.
FYI Pip is a fresh install from debian wheezy repo 

Envoyé de mon iPhone

**Comment by SeanBE** [comment]
Same problem here. @aiusepsi solution works.

**Comment by philippeluickx** [comment]
Same issue here, @aiusepsi solution did not do the trick for me though...

**Comment by diegoaguilar** [comment]
@aiusepsi advice did the trick with fresh installed Ubuntu 12.04.5

**Comment by ninuxhub** [comment]
@aiusepsi ok your solution work for me too

**Comment by amali** [comment]
@philippeluickx  sudo pip install git+https://github.com/xxinfinityxx/robobrowser

**Comment by vivek14632** [comment]
G:\MyProjects\Twitter-data-collection\python-code-to-mine-twitter\tweepy>python
setup.py install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())
TypeError: parse_requirements() got an unexpected keyword argument 'session'

G:\MyProjects\Twitter-data-collection\python-code-to-mine-twitter\tweepy>

**Comment by Nikhil14** [comment]
aiusepsi  solution works for me

**Comment by naresh-chaudhary** [comment]
@aiusepsi 's solution worked for me as well.

**Comment by Luuii** [comment]
the @aiusepsi request it was for me the right solution. Thank you

**Comment by Harmon758** [comment]
This was caused by #534, which uses [a hack](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py/16624700#16624700) to fix #533, caused by [a change](https://github.com/pypa/pip/commit/7037443975ee5706ef829f14a52ac2fba7dbfff2) (https://github.com/pypa/pip/pull/1796) in pip 6.0 that required an HTTP session to be passed even if there weren't any external references by URL to resolve.
However, including this session caused the installation to break for versions of pip <6.0.
Nevertheless, due to [a change](https://github.com/pypa/pip/commit/95bcf8c5f6394298035a7332c441868f3b0169f4#diff-851cc85103a872db421c81afadd4fee5) (https://github.com/pypa/pip/pull/4700) in pip 10.0.0 (see #1029) and the resulting fix by https://github.com/tweepy/tweepy/commit/29e32cdf4a67b1fca25dbf04d7b8069ac1c9dd0d (#1030) in [3.7.0](https://github.com/tweepy/tweepy/releases/tag/3.7.0), this should no longer be a relevant issue.
