### ISSUE TITLE
'JSONParser' object has no attribute 'model_factory'

### ISSUE THREAD

**Issue by atosatto** [tweepy/tweepy#538]
Running the following snippet of code using tweepy 3.1.0

``` python
# Autenticating
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(OAUTH_TOKEN, OAUTH_TOKEN_SECRET)

# API Access
api = tweepy.API(auth, parser=JSONParser(), wait_on_rate_limit=True)

# Dumping the "home" timeline
statuses = []
for s in tweepy.Cursor(api.user_timeline, id=PROFILE_HANDLE).items(10):
    print "We have currently fetched %d tweets" % len(statuses)
    statuses.append(s)

# Writing the output to a file
with open("output.json", "w") as outfile:
    json.dump(statuses, outfile, indent=1)
```

I get this error

```

Traceback (most recent call last):
  File "dumptwitterstream.py", line 32, in <module>
    for s in tweepy.Cursor(api.user_timeline, id=PROFILE_HANDLE).items(10):
  File "/usr/local/lib/python2.7/site-packages/tweepy/cursor.py", line 197, in next
    self.current_page = self.page_iterator.next()
  File "/usr/local/lib/python2.7/site-packages/tweepy/cursor.py", line 117, in next
    model = ModelParser().parse(self.method(create=True), data)
  File "/usr/local/lib/python2.7/site-packages/tweepy/parsers.py", line 95, in parse
    result = model.parse_list(method.api, json)
  File "/usr/local/lib/python2.7/site-packages/tweepy/models.py", line 65, in parse_list
    results.append(cls.parse(api, obj))
  File "/usr/local/lib/python2.7/site-packages/tweepy/models.py", line 81, in parse
    user_model = getattr(api.parser.model_factory, 'user') if api else User
AttributeError: 'JSONParser' object has no attribute 'model_factory'
```

The same code is fully working with tweepy 2.3.0.

**Comment by jschnurr** [comment]
Same problem in 3.3.0.

**Comment by davidsemakula** [comment]
Same issue in 3.3.0

@hilbert- @jschnurr - Currently using this as a work around ... adds a little computation overhead and doesn't include metadata

```python
statuses = []
data = tweepy.Cursor(api.search, **params).items(max)
for status in data:
    statuses.append(status._json)
```

**Comment by josbys1** [comment]
Still having this issue in 3.5

**Comment by oussjarrouse** [comment]
I am having this problem as well...

**Comment by Horatio-Blackwood** [comment]
Same issue here when using json.loads in 3.5

**Comment by tech4242** [comment]
Stuck on this as well & can't revert to 2.3.0 as @davidsemakula suggested (currently using 3.5)

**Comment by jskii** [comment]
+1 to this issue for me as well.

**Comment by AlmuHS** [comment]
Same issue for me

**Comment by Harmon758** [comment]
This should be resolved with https://github.com/tweepy/tweepy/commit/41e7afa3ad4110613e893e5ad459ef72007673a0 in v4.0.0.
