### ISSUE TITLE
Failed to send request: 'str' object has no attribute 'decode' on Ubuntu 16.04

### ISSUE THREAD

**Issue by erltoichi** [tweepy/tweepy#906]
The code attached below generates an error on Ubuntu 16.04 LTS with python3 default package installed (python3 --version returns 3.5.2). 

The error message is: 
«Failed to send request: 'str' object has no attribute 'decode'»

The code works fine on Ubuntu 17.04 and Fedora 25 (both python3 --version returning 3.5.3). The code also runs on Ubuntu 16.04 LTS with self-compiled from source python 3.6.1.
Also, the code has been running ok for over a year on Ubuntu 16.04 LTS - it only fails since mid June 2017.
Not sure where the issue is, probably in Ubuntu package for python or in python version 3.5.2.

```
from datetime import datetime,date,time,timezone
import tweepy as twitter


def sendToTwitter():
        consumer_key='...'
        consumer_secret='...'
        access_token_key='...'
        access_token_secret='..'
        #connect to the twitter api
        message = "tweet test"
        print("trying to send the tweet...")
        try:
                auth = twitter.OAuthHandler(consumer_key, consumer_secret)
                auth.set_access_token(access_token_key, access_token_secret)
                api = twitter.API(auth)
                status = api.update_status(status=message)
                print("tweet sent")
        except Exception as e:
                        print("error while tweeting. reason : " + str(e))
        return
sendToTwitter()
```

**Comment by Harmon758** [comment]
I'm unable to reproduce this, and this doesn't seem like an issue with Ubuntu, Python, or Tweepy.
Can you provide the full traceback?
